import * as THREE from 'three';
import {createTrailer} from './trailer3d.js';
import {trailer, limits, groups, components, routes, steps, sources, operations, toggleLabels} from './data.js';
import {Viewer} from '../src/model.js';
// Generated by work/build-anhaenger.mjs: downscaled photos of the existing system and the decal logo.
import {photos} from '../work/qa/anhaenger-photos.js';
import decalUrl from '../work/qa/logo-decal.png';

const $ = id => document.getElementById(id);
const fmt = n => Math.round(n).toLocaleString('de-DE');
const dec = (n, d = 1) => n.toLocaleString('de-DE', {minimumFractionDigits: d, maximumFractionDigits: d});
const byId = Object.fromEntries(components.map(c => [c.id, c]));
const groupOf = id => groups.find(g => g.id === id);
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
const media = matchMedia('(prefers-color-scheme: dark)');
const isDark = () => {const t = document.documentElement.dataset.theme; return t ? t === 'dark' : media.matches;};

let view3d = null, kit = null, currentView = 'cut';
const filmMode = new URLSearchParams(location.search).has('film');
if (filmMode) {
 document.body.classList.add('film');
 $('stage').insertAdjacentHTML('beforeend', `<div class="filmcap" id="filmCap"><i></i><b></b><span></span></div>
  <div class="filmcard" id="filmCard"><img alt="DiTom Kanaltechnik" src="${decalUrl}"><h2></h2><p></p></div>`);
 window.__film = {
  caption: (title, sub, a) => {const c = $('filmCap'); c.querySelector('b').textContent = title || ''; c.querySelector('span').textContent = sub || ''; c.style.opacity = a; c.style.transform = `translateY(${(1 - a) * 14}px)`;},
  card: (title, sub, a) => {const c = $('filmCard'); c.querySelector('h2').textContent = title || ''; c.querySelector('p').textContent = sub || ''; c.style.opacity = a;},
 };
}

// ---------- 3D ----------
const logo = new Image(); logo.src = decalUrl;
logo.decode().catch(() => {}).finally(() => {
 try {
  view3d = createTrailer($('stage'), {logo, logoRatio: logo.naturalHeight / logo.naturalWidth || .34,
   onSelect: (id, focus) => select(id, focus ? 'badge' : 'model'),
   onToggle: () => syncOps(),
   onView: v => showView(v)});
 } catch (e) {
  $('err').hidden = false; $('err').textContent = 'Die 3D-Ansicht konnte nicht gestartet werden (WebGL). Alle Angaben in der Seitenleiste bleiben nutzbar.';
  console.error(e); return;
 }
 applyTheme(); update(); syncOps(); window.__trailer = view3d;
 if (innerWidth < 600 && !filmMode) {view3d.setOption('numbers', false); syncOptions();} // small screens: badges off, parts stay clickable
 // real DSS-Flex moulds for the pull-out, built with the existing model (robot hidden)
 setTimeout(() => {try {view3d.setMoulds(buildMoulds([300, 400]));} catch (e) {console.warn('Schalungsmodelle', e);}}, 900);
});
function applyTheme() {view3d?.setTheme(isDark()); kit?.setTheme(isDark());}
media.addEventListener('change', applyTheme); new MutationObserver(applyTheme).observe(document.documentElement, {attributes: true, attributeFilter: ['data-theme']});

const viewText = {
 cut: ['01 · Offener Schnitt', 'Jedes Teil an seinem Platz.', 'Dach und rechte Wand ausgeblendet. Teile anklicken – Schubladen und Türen lassen sich öffnen.'],
 exterior: ['02 · Fahrstellung', 'Geschlossen und gesichert.', 'Alles verriegelt, Markise und Stützen eingefahren, Mischpumpe verzurrt.'],
 work: ['03 · Arbeitsstellung', 'Aufgebaut für den Einsatz.', 'Hecktüren 270° an den Seiten, Markise als Regendach, Stützen unten, Mischpumpe draußen.'],
 plan: ['04 · Grundriss', 'Zonen von vorn nach hinten.', 'Technik · Schalungen · Wasser über den Achsen · Mörtel und Reinigung am Heck.'],
 kit: ['05 · DSS-Flex Schalung', 'Was im Auszug liegt.', 'Sanierungsaufsatz ohne Roboter · Baugröße wählbar · Explosionsansicht.'],
 walk: ['06 · Begehen', 'Über den Klapptritt hinein.', 'Durch die Seitentür in den Mittelgang, Schubladen per Klick öffnen.'],
};
function showView(v) {
 currentView = v;
 document.querySelectorAll('[data-view]').forEach(b => b.setAttribute('aria-pressed', b.dataset.view === v));
 const [l, h, s] = viewText[v]; $('viewLabel').textContent = l; $('viewHeading').textContent = h; $('viewSub').textContent = s;
 const k = v === 'kit', w = v === 'walk';
 $('kit').hidden = !k; $('kitTools').hidden = !k; $('walkUI').hidden = !w; $('bottom').hidden = k || w; $('sceneTitle').hidden = w; $('ops').hidden = k;
 $('stage').querySelector('canvas').style.visibility = k ? 'hidden' : ''; $('stage').querySelector('.overlay').hidden = k;
 if (kit) kit.paused = !k; view3d?.setPaused(k);
 syncOptions();
}
function syncOptions() {const s = view3d?.state; if (!s) return; document.querySelectorAll('[data-opt]').forEach(i => i.checked = !!s[i.dataset.opt]); $('legend').hidden = !s.routes;}
document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => {
 const v = b.dataset.view;
 if (v === 'kit') {openKit(); showView('kit'); return;}
 if (v === 'walk') {view3d?.enterWalk(); showView('walk'); return;}
 view3d?.setView(v); showView(v);
}));
$('reset').addEventListener('click', () => {view3d?.setView('cut'); showView('cut');});
document.querySelectorAll('[data-opt]').forEach(i => i.addEventListener('change', () => {view3d?.setOption(i.dataset.opt, i.checked); syncOptions();}));
$('legend').innerHTML = routes.map(r => `<span><i style="background:${r.color}"></i>${r.label}</span>`).join('');

// ---------- operate: doors, awning, legs, mixer, drawers ----------
$('ops').innerHTML = `<span class="opslabel">Bedienen</span>` + operations.map(o => `<button type="button" data-op="${o.id}" aria-pressed="false">${o.label}</button>`).join('');
document.querySelectorAll('[data-op]').forEach(b => b.addEventListener('click', () => {
 const o = operations.find(x => x.id === b.dataset.op), st = view3d?.toggles || {}, on = !o.toggles.every(t => st[t]);
 if (currentView === 'kit' || currentView === 'plan') {view3d?.setView('cut'); showView('cut');}
 for (const t of o.toggles) view3d?.toggle(t, on);
}));
function syncOps() {
 const st = view3d?.toggles || {};
 document.querySelectorAll('[data-op]').forEach(b => {const o = operations.find(x => x.id === b.dataset.op); b.setAttribute('aria-pressed', o.toggles.every(t => st[t]));});
 document.querySelectorAll('[data-tg]').forEach(b => {const on = !!st[b.dataset.tg]; b.setAttribute('aria-pressed', on); b.querySelector('.st').textContent = on ? 'schließen' : 'öffnen';});
}

// walk controls
$('walkExit').addEventListener('click', () => {view3d?.setView('cut'); showView('cut');});
$('walkReset').addEventListener('click', () => view3d?.resetWalk());
$('walkTurn').addEventListener('click', () => view3d?.turn(Math.PI));
{
 const pad = $('stick'), knob = pad.firstElementChild; let id = null;
 const move = e => {const r = pad.getBoundingClientRect(), x = (e.clientX - r.left) / r.width * 2 - 1, y = (e.clientY - r.top) / r.height * 2 - 1, l = Math.max(1, Math.hypot(x, y)); knob.style.transform = `translate(${x / l * 34}px,${y / l * 34}px)`; view3d?.setStick(x / l, y / l);};
 pad.addEventListener('pointerdown', e => {id = e.pointerId; pad.setPointerCapture(id); move(e);});
 pad.addEventListener('pointermove', e => {if (e.pointerId === id) move(e);});
 const end = () => {id = null; knob.style.transform = ''; view3d?.setStick(0, 0);};
 pad.addEventListener('pointerup', end); pad.addEventListener('pointercancel', end);
}

// ---------- kit view (existing DSS-Flex model, robot hidden) ----------
class KitViewer extends Viewer {
 animate() {if (this.paused) {requestAnimationFrame(() => this.animate()); this.last = performance.now(); return;} super.animate();}
}
const partGroups = {s: 'Schalung', h: 'Halteeinheit', z: 'Zentraleinheit', u: 'Unterteil'};
function ensureKit() {
 if (kit) return kit;
 kit = new KitViewer($('kit'), p => {kit.select(p); $('kitPart').textContent = `${partGroups[p.group] || ''} · Pos. ${p.pos} · ${p.name}${p.qty > 1 ? ` (${p.qty}×)` : ''}`;});
 kit.paused = currentView !== 'kit'; kit.setTheme(isDark()); kit.setSections({hideRobot: true});
 return kit;
}
function openKit(size) {
 ensureKit();
 const dn = +(size || $('kitSize').value); $('kitSize').value = String(dn);
 kit.paused = false; kit.build(dn); kit.setMode('explore'); kit.setSections({hideRobot: true}); kit.setExplode(+$('kitExplode').value / 100); kit.fitExplosion?.(); kit.fit();
 $('kitPart').textContent = 'Teil anklicken für Bezeichnung';
}
// Copy only visible geometry (userData of the kit viewer holds circular part references).
function cloneVisible(src) {
 const dst = src.isMesh ? new THREE.Mesh(src.geometry.clone(), Array.isArray(src.material) ? src.material.map(m => m.clone()) : src.material.clone()) : new THREE.Group();
 dst.position.copy(src.position); dst.quaternion.copy(src.quaternion); dst.scale.copy(src.scale);
 if (dst.material && !Array.isArray(dst.material)) dst.material.clippingPlanes = null;
 for (const c of src.children) if (c.visible && !c.isInstancedMesh && (c.isMesh || c.isGroup || c.type === 'Object3D')) dst.add(cloneVisible(c));
 return dst;
}
function buildMoulds(list) {
 const k = ensureKit(), out = {};
 for (const dn of list) {
  k.build(dn); k.setMode('explore'); k.setSections({hideRobot: true}); k.targetExplode = 0; k.explode = 0; k.updateParts(); k.model.updateMatrixWorld(true);
  out[dn] = cloneVisible(k.model);
 }
 if (currentView === 'kit') openKit();
 return out;
}
$('kitSize').addEventListener('change', () => openKit());
$('kitExplode').addEventListener('input', e => kit?.setExplode(+e.target.value / 100));

// ---------- tabs ----------
function openTab(t) {
 document.querySelectorAll('[data-tab]').forEach(b => b.setAttribute('aria-selected', b.dataset.tab === t));
 document.querySelectorAll('.panel').forEach(p => p.hidden = p.id !== t);
 if (t === 'supply' && view3d && !view3d.state.routes) {view3d.setOption('routes', true); syncOptions();}
}
document.querySelectorAll('[data-tab]').forEach(b => b.addEventListener('click', () => openTab(b.dataset.tab)));

// ---------- zones + component card ----------
const zones = [
 ['Vorn · Technik', 'Aggregat im belüfteten Technikfach, Unterverteilung, Kompressorregal – schwer und laut, trägt die Stützlast.', 'energie'],
 ['Seitentür · Einstieg', 'Klapptritt, freie Standfläche, Verkehrssicherung und Feuerlöscher griffbereit.', 'aussen'],
 ['Mitte · Schalungen', 'Schwerlastauszug mit DN 300/400, Wechselschilde am Sattel, Blasen unter der Decke.', 'schalung'],
 ['Über den Achsen · Wasser', '2 × 300 l links und rechts, darüber Mörtelsäcke und Werkbank.', 'wasser'],
 ['Heck · Arbeit', 'Trommel, Verteiler, Hochdruck, Mischplatz – die Mischpumpe rollt über Rampen unter die Markise.', 'moertel'],
];
$('zones').innerHTML = zones.map(([t, d, g]) => `<div><i style="background:${groupOf(g).color}"></i><b>${t}</b><span>${d}</span></div>`).join('');
const chassisInfo = {n: '00', title: 'Tandem-Kofferanhänger 3,5 t', group: null, place: 'Fahrgestell & Aufbau', mass: trailer.emptyMass,
 desc: 'Gebremster Tandem-Hochlader mit verzinktem Fahrgestell, V-Deichsel, Auflaufeinrichtung mit Stabilisierungskupplung, Stützrad und Deichselbox. GFK-Sandwichkoffer mit Aluminium-Rillenboden, Airline-Schienen, Kabelkanälen und LED-Deckenleuchten; zwei 270°-Hecktüren mit Drehstangenverschluss, Seitentür auf der Gehwegseite, Rundumkennleuchte.',
 spec: [[`${dec(trailer.inner.length, 2)} × ${dec(trailer.inner.width, 2)} × ${dec(trailer.inner.height, 2)} m`, 'Innenmaß'], ['3.500 kg', 'zul. Gesamtmasse'], [`ca. ${fmt(trailer.emptyMass)} kg`, 'Leergewicht (Schätzung)'], ['0,76 m', 'Ladehöhe']], photos: [], toggles: ['doorL', 'doorR']};
const stepsFor = id => steps.filter(s => s.uses.includes(id));
const photoUse = {};
for (const c of components) for (const f of c.photos) (photoUse[f] ||= []).push(c);
function photoCaption(f) {const u = photoUse[f]; return u ? u.map(c => `${c.n} ${c.title}`).join(' · ') : 'Übersicht alte Anlage';}
function photoFigure(list) {
 if (!list.length) return '';
 return `<div class="thumbs">${list.map(f => `<button type="button" class="thumb" data-photo="${f}" aria-label="Foto der alten Anlage vergrößern"><img src="${photos[f]}" alt="Alte Anlage: ${photoCaption(f)}" loading="lazy"></button>`).join('')}</div><p class="thumbcap">Vorbild in der bestehenden Anlage</p>`;
}
function toggleButtons(c) {
 const list = (c.toggles || []).filter(t => !(c.drawers || []).some(d => d.id === t));
 if (!list.length) return '';
 return `<div class="tgs">${list.map(t => `<button type="button" class="tg" data-tg="${t}" aria-pressed="false"><b>${toggleLabels[t]}</b><span class="st">öffnen</span></button>`).join('')}</div>`;
}
function drawerList(c) {
 if (!c.drawers?.length) return '';
 return `<div class="drawers">${c.drawers.map(d => `<div class="drw"><button type="button" class="tg" data-tg="${d.id}" aria-pressed="false"><b>${d.title}</b><span class="st">öffnen</span></button><ul>${d.items.map(i => `<li>${i}</li>`).join('')}</ul></div>`).join('')}</div>`;
}
function select(id, from) {
 const c = id === 'chassis' ? chassisInfo : byId[id];
 const sel = c ? id : null;
 view3d?.select(sel, from === 'list' || from === 'badge');
 document.querySelectorAll('.comp').forEach(el => el.setAttribute('aria-current', el.dataset.id === id));
 if (!c) {$('card').innerHTML = defaultCard; return;}
 const g = c.group ? groupOf(c.group) : null;
 const mass = c.variable === 'water' ? `${fmt(c.mass)} kg + Wasser` : c.variable === 'bags' ? `${fmt(c.mass)} kg + Säcke` : c.variable === 'wash' ? `${fmt(c.mass)} kg + Waschwasser` : `${fmt(c.mass)} kg`;
 const used = c.group ? stepsFor(id) : [];
 $('card').innerHTML = `
  <div class="cardhead"><span class="badge-n num" style="background:${g ? g.color : 'var(--ink)'}">${c.n}</span><div><h3>${c.title}</h3><p class="caption">${g ? g.name : 'Fahrzeug'} · ${c.place}</p></div></div>
  <p class="desc">${c.desc}</p>
  ${toggleButtons(c)}${drawerList(c)}
  <div class="spec">${c.spec.map(([v, l]) => `<div><strong>${v}</strong><span>${l}</span></div>`).join('')}<div><strong class="num">${mass}</strong><span>Masse</span></div></div>
  ${used.length ? `<p class="uses">Im Ablauf: ${used.map(s => `<button type="button" class="chip" data-step="${s.n}">${s.n} · ${s.title}</button>`).join('')}</p>` : ''}
  ${photoFigure(c.photos || [])}
  <div class="cardbtns">${view3d ? `<button type="button" class="btn" id="focusBtn">Im Modell zeigen</button>` : ''}${c.kit ? `<button type="button" class="btn ghost" id="kitBtn">Schalung ${c.kit === 400 ? 'DN 400' : 'DN 600'} öffnen</button>` : ''}</div>`;
 $('focusBtn')?.addEventListener('click', () => {if (currentView === 'kit' || currentView === 'walk' || currentView === 'plan') {view3d.setView('cut'); showView('cut');} view3d.select(id, true);});
 $('kitBtn')?.addEventListener('click', () => {openKit(c.kit); showView('kit');});
 $('card').querySelectorAll('[data-tg]').forEach(b => b.addEventListener('click', () => {if (currentView === 'kit' || currentView === 'plan') {view3d?.setView('cut'); showView('cut');} view3d?.toggle(b.dataset.tg); if (currentView !== 'walk') view3d?.select(id, true);}));
 $('card').querySelectorAll('[data-step]').forEach(b => b.addEventListener('click', () => {openTab('process'); const el = $('step-' + b.dataset.step); el?.scrollIntoView({behavior: reduced ? 'auto' : 'smooth', block: 'center'}); el?.classList.add('flash'); setTimeout(() => el?.classList.remove('flash'), 1400);}));
 bindThumbs($('card')); syncOps();
 if (from === 'model' || from === 'badge') {openTab('parts'); $('card').scrollIntoView({behavior: reduced ? 'auto' : 'smooth', block: 'nearest'});}
}
const defaultCard = `<div class="cardhead"><span class="badge-n num">i</span><div><h3>Bauteil wählen</h3><p class="caption">Nummer im Modell, Klick auf ein Teil oder Eintrag in der Liste</p></div></div><p class="desc">Schubladen, Eurokisten, Türen, Klappen, Markise, Stützen und die Mischpumpe lassen sich direkt im Modell anklicken und öffnen. Die Leiste „Bedienen“ schaltet ganze Gruppen.</p>`;
$('card').innerHTML = defaultCard;
$('list').innerHTML = groups.map(g => `<section class="grp"><h4><i style="background:${g.color}"></i>${g.name}</h4>${components.filter(c => c.group === g.id).map(c => `<button type="button" class="comp" data-id="${c.id}"><span class="num">${c.n}</span><span class="t">${c.title}<small>${c.place}</small></span><em class="num">${fmt(c.mass)} kg</em></button>`).join('')}</section>`).join('')
 + `<section class="grp"><h4><i style="background:var(--ink)"></i>Fahrzeug</h4><button type="button" class="comp" data-id="chassis"><span class="num">00</span><span class="t">${chassisInfo.title}<small>${chassisInfo.place}</small></span><em class="num">${fmt(trailer.emptyMass)} kg</em></button></section>`;
document.querySelectorAll('.comp').forEach(b => b.addEventListener('click', () => select(b.dataset.id, 'list')));

// ---------- process ----------
$('steps').innerHTML = steps.map(s => `<li id="step-${s.n}"><span class="n num">${s.n}</span><div><h4>${s.title}</h4><p>${s.text}</p><p class="uses">${s.uses.map(id => `<button type="button" class="chip" data-id="${id}"><i style="background:${groupOf(byId[id].group).color}"></i>${byId[id].n} ${byId[id].title.replace(/ \d.*$/, '').replace(/ – .*$/, '')}</button>`).join('')}</p><button type="button" class="btn small" data-show="${s.n}">Im Modell zeigen</button></div></li>`).join('');
$('steps').querySelectorAll('[data-id]').forEach(b => b.addEventListener('click', () => {select(b.dataset.id, 'list'); openTab('parts');}));
$('steps').querySelectorAll('[data-show]').forEach(b => b.addEventListener('click', () => {
 const s = steps.find(x => x.n === +b.dataset.show); if (!view3d) return;
 if (currentView === 'kit' || currentView === 'walk' || currentView === 'plan') {view3d.setView('cut'); showView('cut');}
 view3d.setStates(s.state); view3d.select(s.uses[0], true);
}));

// ---------- supply ----------
const routeText = {
 water: ['Tank links ⇄ Tank rechts (unter dem Boden) → Filter → Hauswasserwerk → Hochdruckreiniger → Edelstahl-Haspel', 'Zweiter Abgang vom Hauswasserwerk über die Decke zur Zapfstelle am Mischplatz. Befüllung außen über die C-Kupplung links.'],
 air: ['Kompressor → Wartungseinheit → PA-Ringleitung rechte Wand → Heckdecke → Verteiler → Drehdurchführung der Trommel → Schalung', 'Wandkupplungen an der Seitentür, an der Werkbank, am Mischplatz und am Heck (Spiralschlauch). Vakuum als eigene schwarze Leitung zum Verteiler.'],
 mortar: ['Mischpumpe (draußen unter der Markise) → Mörtelschlauch → Messingwinkel → Opferschlauch an der Schalung', 'Die Pumpe rollt über die Klapprampen aus dem Mischplatz – der Mörtelweg bleibt kurz und trocken.'],
 power: ['Aggregat oder CEE-32-A-Einspeisung → Umschalter → Unterverteilung mit FI je Kreis → Kabelkanäle unter der Decke', 'Steckdosen an Werkbank, Mischplatz (CEE 16 A), Hochdruckplatz, Heck und außen; Hilfsakku für Licht bei stehendem Aggregat.'],
};
$('routeList').innerHTML = routes.map(r => `<div class="route"><i style="background:${r.color}"></i><div><b>${r.label}</b><p class="path">${routeText[r.kind][0]}</p><p>${routeText[r.kind][1]}</p></div></div>`).join('');
const phases = [
 ['Schalung setzen', [['Kompressor', 2.2], ['Vakuumpumpe', .4], ['Licht', .3]]],
 ['Verpressen', [['Mischpumpe (Annahme)', 4.0], ['Rührwerk', 1.6], ['Kompressor', 2.2], ['Licht', .3]]],
 ['Reinigen', [['Hochdruckreiniger', 6.5], ['Hauswasserwerk', .9], ['Licht', .3]]],
];
const genKw = 12 * .8;
$('power').innerHTML = phases.map(([name, list]) => {const sum = list.reduce((s, [, k]) => s + k, 0), pct = Math.min(100, sum / genKw * 100);
 return `<div class="phase"><div class="row"><b>${name}</b><strong class="num">${dec(sum)} kW</strong></div><div class="meter"><span class="fill ${sum > genKw ? 'bad' : sum > genKw * .85 ? 'warn' : 'ok'}" style="width:${pct}%"></span></div><p>${list.map(([n, k]) => `${n} ${dec(k)}`).join(' · ')}</p></div>`;}).join('')
 + `<p class="copy small">Aggregat 12 kVA ≈ ${dec(genKw)} kW bei cos φ 0,8. Hochdruck und Mischpumpe laufen nie gleichzeitig; Anlaufströme der Pumpe beim Hersteller erfragen.</p>`;

// ---------- load calculator ----------
const axle = (trailer.axleX[0] + trailer.axleX[1]) / 2, lever = trailer.couplingX - axle;
const presets = {anfahrt: {water: 300, bags: 10, wash: 0}, voll: {water: 600, bags: 6, wash: 0}, rueck: {water: 40, bags: 2, wash: 70}};
const inputs = () => ({water: +$('water').value, bags: +$('bags').value, wash: +$('wash').value});
document.querySelectorAll('[data-preset]').forEach(b => b.addEventListener('click', () => {
 document.querySelectorAll('[data-preset]').forEach(x => x.setAttribute('aria-pressed', x === b));
 const p = presets[b.dataset.preset]; $('water').value = p.water; $('bags').value = p.bags; $('wash').value = p.wash; update();
}));
['water', 'bags', 'wash'].forEach(id => $(id).addEventListener('input', () => {document.querySelectorAll('[data-preset]').forEach(x => x.setAttribute('aria-pressed', 'false')); update();}));
function compute(p) {
 const items = [{g: 'fahrzeug', m: trailer.emptyMass + trailer.fitOut, x: trailer.emptyCgX}, ...components.map(c => ({g: c.group, m: c.mass, x: c.x})),
  {g: 'wasser', m: p.water, x: byId.tankL.x}, {g: 'moertel', m: p.bags * 25, x: byId.bags.x}, {g: 'moertel', m: p.wash, x: byId.settle.x}];
 const mass = items.reduce((s, i) => s + i.m, 0), tongue = items.reduce((s, i) => s + i.m * (i.x - axle), 0) / lever;
 const perGroup = {}; for (const i of items) perGroup[i.g] = (perGroup[i.g] || 0) + i.m;
 return {mass, tongue, axleLoad: mass - tongue, minTongue: Math.min(limits.tongueMinAbs, .04 * mass), perGroup};
}
function update() {
 const p = inputs(), r = compute(p);
 $('waterOut').textContent = `${fmt(p.water)} l`; $('bagsOut').textContent = `${p.bags} × 25 kg`; $('washOut').textContent = `${fmt(p.wash)} l`;
 $('totals').innerHTML = `<div><strong class="num">${fmt(r.mass)}</strong><span>kg Anhänger</span></div><div><strong class="num">${fmt(r.tongue)}</strong><span>kg Stützlast</span></div><div><strong class="num">${fmt(r.axleLoad)}</strong><span>kg auf den Achsen</span></div>`;
 const tOk = r.tongue >= r.minTongue && r.tongue <= limits.tongueMax;
 const checks = [
  {label: 'Gesamtmasse', value: r.mass, max: limits.gvw, text: `zul. ${fmt(limits.gvw)} kg`, st: r.mass <= limits.gvw - 100 ? 'ok' : r.mass <= limits.gvw ? 'warn' : 'bad'},
  {label: 'Stützlast', value: r.tongue, max: limits.tongueMax, min: r.minTongue, text: `${fmt(r.minTongue)}–${limits.tongueMax} kg (Kupplung Zugfahrzeug)`, st: !tOk ? 'bad' : r.tongue > limits.tongueMax - 15 || r.tongue < r.minTongue + 10 ? 'warn' : 'ok'},
 ];
 $('checks').innerHTML = checks.map(c => {const span = c.max * 1.15, pct = Math.max(0, Math.min(100, c.value / span * 100));
  return `<div class="check ${c.st}"><div class="row"><span>${c.label}</span><strong class="num">${fmt(c.value)} kg</strong></div><div class="meter" role="img" aria-label="${c.label} ${fmt(c.value)} kg, ${c.text}"><span class="fill ${c.st}" style="width:${pct}%"></span><span class="lim" style="left:${c.max / span * 100}%"></span>${c.min ? `<span class="lim" style="left:${c.min / span * 100}%"></span>` : ''}</div><div class="row subrow"><span>${c.text}</span><span class="pill">${c.st === 'ok' ? 'in Ordnung' : c.st === 'warn' ? 'knapp' : 'nicht zulässig'}</span></div></div>`;}).join('');
 const notes = [];
 if (r.mass > limits.gvw) notes.push(['bad', `<b>${fmt(r.mass - limits.gvw)} kg zu schwer.</b> Tanks erst am Einsatzort füllen oder weniger Säcke laden.`]);
 else if (p.water > 400) notes.push(['warn', `<b>Volle Tanks nur mit wenigen Säcken.</b> Mit ${fmt(p.water)} l bleiben ${fmt(limits.gvw - r.mass)} kg Reserve.`]);
 if (r.tongue < r.minTongue) notes.push(['bad', '<b>Stützlast zu gering.</b> Waschwasser vor der Fahrt ablassen.']);
 if (r.tongue > limits.tongueMax) notes.push(['bad', '<b>Stützlast zu hoch.</b> Schwere Lasten weiter zur Achse laden.']);
 if (!notes.length) notes.push(['ok', '<b>Fahrbereit.</b> Masse und Stützlast liegen im Rahmen. Stützlast vor jeder Fahrt an der Deichsel prüfen.']);
 const dWater = 600 * (byId.tankL.x - axle) / lever;
 notes.push(['', `Die Wassertanks sitzen zwischen den Achsen: 600 l ändern die Stützlast nur um ${fmt(Math.abs(dWater))} kg, die Gesamtmasse aber um 600 kg.`]);
 $('notes').innerHTML = notes.map(([c, t]) => `<li class="${c}">${t}</li>`).join('');
 const names = {fahrzeug: 'Fahrzeug + Ausbau', ...Object.fromEntries(groups.map(g => [g.id, g.name]))};
 $('masses').innerHTML = `<tbody>${Object.entries(r.perGroup).map(([g, m]) => `<tr><th scope="row"><i style="background:${g === 'fahrzeug' ? 'var(--ink)' : groupOf(g).color}"></i>${names[g]}</th><td class="num">${fmt(m)} kg</td></tr>`).join('')}<tr class="sum"><th scope="row">Summe</th><td class="num">${fmt(r.mass)} kg</td></tr></tbody>`;
 view3d?.setLoad({water: p.water, bags: p.bags, wash: p.wash});
}
update();

// ---------- photos + lightbox ----------
const allPhotos = Object.keys(photos).sort();
$('gallery').innerHTML = allPhotos.map(f => `<button type="button" class="thumb" data-photo="${f}"><img src="${photos[f]}" alt="Alte Anlage: ${photoCaption(f)}" loading="lazy"><span>${photoCaption(f)}</span></button>`).join('');
let lbIndex = 0;
function openPhoto(f) {lbIndex = allPhotos.indexOf(f); showPhoto(); $('lightbox').showModal();}
function showPhoto() {const f = allPhotos[(lbIndex % allPhotos.length + allPhotos.length) % allPhotos.length]; $('lbImg').src = photos[f]; $('lbImg').alt = 'Alte Anlage: ' + photoCaption(f); $('lbCap').textContent = photoCaption(f);}
$('lbPrev').addEventListener('click', () => {lbIndex--; showPhoto();}); $('lbNext').addEventListener('click', () => {lbIndex++; showPhoto();});
$('lightbox').addEventListener('keydown', e => {if (e.key === 'ArrowLeft') {lbIndex--; showPhoto();} if (e.key === 'ArrowRight') {lbIndex++; showPhoto();}});
$('lightbox').addEventListener('click', e => {if (e.target === $('lightbox')) $('lightbox').close();});
function bindThumbs(root) {root.querySelectorAll('[data-photo]').forEach(b => b.addEventListener('click', () => openPhoto(b.dataset.photo)));}
bindThumbs($('gallery'));

// ---------- sources ----------
$('srclist').innerHTML = Object.values(sources).map(([t, u]) => `<li><a href="${u}" target="_blank" rel="noopener">${t}</a></li>`).join('');
