import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import esbuild from 'esbuild';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const result=await esbuild.build({absWorkingDir:root,tsconfigRaw:{},entryPoints:['src/main.js'],bundle:true,write:false,minify:true,format:'iife',target:['chrome100','firefox110','safari16'],legalComments:'inline'});
const css=await readFile(path.join(root,'src/style.css'),'utf8');const template=await readFile(path.join(root,'src/index.template.html'),'utf8');
const logo=await readFile(path.join(root,'src/logo-transparent.png'));
const html=template.replace('/*LOGO_DATA*/',()=>`data:image/png;base64,${logo.toString('base64')}`).replace('/*STYLES*/',()=>css).replace('/*APP*/',()=>result.outputFiles[0].text.replaceAll('</script','<\\/script'));
await writeFile(path.join(root,'DSS-Flex-Verfahren-Praesentation.html'),html);
await writeFile(path.join(root,'index.html'),html);
await writeFile(path.join(root,'Kanaltec-4.0-Praesentation.html'),'<!doctype html><html lang="de"><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=./DSS-Flex-Verfahren-Praesentation.html"><title>DSS-Flex Verfahren</title><a href="./DSS-Flex-Verfahren-Praesentation.html">DSS-Flex Verfahren öffnen</a></html>');
console.log('Built standalone HTML:',(html.length/1048576).toFixed(2),'MB');
const preview=await esbuild.build({absWorkingDir:root,tsconfigRaw:{},entryPoints:['src/cutter-preview.js'],bundle:true,write:false,minify:true,format:'iife',target:['chrome100','firefox110','safari16'],legalComments:'inline'});
const previewTemplate=await readFile(path.join(root,'src/cutter-preview.template.html'),'utf8'),reference=await readFile(path.join(root,'references/fraeskopf-nutzerfoto.jpg'));
await writeFile(path.join(root,'Fraeskopf-Vergleich.html'),previewTemplate.replace('/*REFERENCE*/',()=>`data:image/jpeg;base64,${reference.toString('base64')}`).replace('/*APP*/',()=>preview.outputFiles[0].text.replaceAll('</script','<\\/script')));
console.log('Built local cutter comparison.');
